# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  About: /about
rss: /atom.xml

since: 2012

# Set default keywords (Use a comma to separate)
keywords: ""

# Put your favicon.ico or avatar.jpg into `hexo-site/themes/hiker/source/` directory.
avatar:
  enable: true
  border: true
  width: 100
  height: 100
  top: 0
  url: css/images/mylogo.png

# Homepage
# eg. home_background_image: [css/images/home-bg.jpg, http://t.cn/RMbvEza]
# eg. mode: image | polyline | trianglify
home_background_image:
  enable: true
  mode: image
  rolling: true
  url: [css/images/home-bg.jpg, css/images/sample.jpg, https://source.unsplash.com/collection/954550/1920x1080] # [css/images/home-bg.jpg, css/images/sample.jpg, https://source.unsplash.com/collection/954550/1920x1080]
  linear: ['linear-gradient(to right, #00dbde 0%, #fc00ff 100%)',
'linear-gradient(to right, #f9d423 0%, #ff4e50 100%)',
'linear-gradient(to top, #50cc7f 0%, #f5d100 100%)',
'linear-gradient(to top, #65bd60 0%, #5ac1a8 25%, #3ec6ed 50%, #b7ddb7 75%, #fef381 100%)',
'linear-gradient(to top, #3f51b1 0%, #5a55ae 13%, #7b5fac 25%, #8f6aae 38%, #a86aa4 50%, #cc6b8e 62%, #f18271 75%, #f3a469 87%, #f7c978 100%)',
'linear-gradient(to top, #f43b47 0%, #453a94 100%)',
'linear-gradient(to top, #0250c5 0%, #d43f8d 100%)',
'linear-gradient(to top, #88d3ce 0%, #6e45e2 100%)',
'linear-gradient(15deg, #13547a 0%, #80d0c7 100%)',
'linear-gradient(to top, #ff0844 0%, #ffb199 100%)',
'linear-gradient(to top, #f3e7e9 0%, #e3eeff 99%, #e3eeff 100%)',
'linear-gradient(to top, #fbc2eb 0%, #a6c1ee 100%)',
'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
'linear-gradient(to top, #fddb92 0%, #d1fdff 100%)',
'linear-gradient(to top, #37ecba 0%, #72afd3 100%)',
'linear-gradient(to top, #fff1eb 0%, #ace0f9 100%)',
'linear-gradient(to top, #df89b5 0%, #bfd9fe 100%)',]

home_logo_image:
  enable: false
  border: false
  url: css/images/homelogo.jpg

# AboutPage background
about_big_image: [1,2] # https://source.unsplash.com/collection/954550/1920x1080

# Archive pagination
archive_pagination: true

# Post Article's Content
post_catalog:
  enable: true
# 开启主页摘要
post_excerpt: true

# Content
fancybox: true

# Sidebar
sidebar: right
widgets:
  - social
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# Social Links
# Key is the name of FontAwsome icon.
social:
  Github:
  Weibo:
  Twitter:
  Facebook:
  Google-plus:
  Instagram:
  Pinterest:
  Flickr:
  email:

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  swiftype: # enter swiftype install key here
  baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# comment ShortName, you can choose only ONE to display.
gentie_productKey: #your-gentie-product-key
duoshuo_shortname:
disqus_shortname:
livere_shortname: # MTAyMC8yOTQ4MS82MDQ5
uyan_uid:
wumii:

# Code Highlight theme
# Available value:
#    default | gray | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: default

# Article theme color
# Available value:
#    random | orange | blue | red | green | black
theme_color: orange

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: "monthly"
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:
baidu_site_verification:
qihu_site_verification:

# Miscellaneous
google_analytics:
gauges_analytics:
baidu_analytics:
tencent_analytics:
twitter:
google_plus:
fb_admins:
fb_app_id:

# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id: #<app_id>
  fb_admin: #<user_id>
  like_button: #true
  webmaster: #true

# CNZZ count
cnzz_siteid: 1260716016

# busuanzi count
# http://busuanzi.ibruce.info/
show_busuanzi_view_counts: false # true

# donation button
donate:
  enable: false
  message: "如果觉得我的文章对您有用，请随意打赏。您的支持将鼓励我继续创作!"
  wechatImage: /css/images/WeChanQR.jpg
  alipayImage: /css/images/AliPayQR.jpg

# post copyright
copyright:
  enable: false

# post edit url, modify your post online for convenience
# If you put your blog on GitHub, it should look like:
# https://github.com/username/blog/edit/master/source/_posts/
post_edit_url:
